# Create a .github/workflows folder inside the local working directory:
# Then create or copy this files main.yml with these configurations:

# This is a basic workflow to help you get started with Actions

name: CI/CD Semantic Workflows

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
    pull_request:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.17

            - name: Install Dependencies
              run: yarn install

            - name: Build App
              run: yarn build

            - name: Launch Semantic Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              run: npx semantic-release
